name: Biocontainer API publish Docker image
env:
  IMAGE_NAME: biocontainer-web

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo envs
        run: |
          echo $IMAGE_TAG
          echo $GITHUB_ACTOR
          echo $GITHUB_REPOSITORY
      - name: Build the Docker image
        run: |
          pwd
          docker build --build-arg CACHEBUST=$(date +%s) --tag $IMAGE_NAME:$GITHUB_SHA .
          docker tag $IMAGE_NAME:$GITHUB_SHA docker.pkg.github.com/$GITHUB_REPOSITORY/$IMAGE_NAME:$GITHUB_SHA
          docker tag $IMAGE_NAME:$GITHUB_SHA ${{ secrets.DOCKERHUB_USER }}/$IMAGE_NAME:$GITHUB_SHA
      - name: push docker image to github
        run: |
          USERNAME=`echo $GITHUB_REPOSITORY | cut -d'/' -f1`
          docker login https://docker.pkg.github.com -u $USERNAME -p ${{ secrets.GITHUB_TOKEN }}
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/$IMAGE_NAME:$GITHUB_SHA
      - name: push docker image to dockerhub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PWD }}
          docker push ${{ secrets.DOCKERHUB_USER }}/$IMAGE_NAME:$GITHUB_SHA